// const productos = [
//   // TABLAS

//   {
//     id: 1,
//     category: "tablas",
//     categoryId: 1,
//     img: "https://i.ibb.co/hmgGtM1/modShell.jpg",
//     img2: "",
//     img3: "",
//     title: "Mod.Shell - Balance Boards",
//     description: "Tablas de equilibrio Hechas a Mano Modelo Surfer",
//     stock: "5",
//     offerPrice: 5999.99,
//     listPrice: 6999.99,
//     cuotas: (5999.99 / 12).toFixed(2),
//   },

//   {
//     id: 2,
//     category: "tablas",
//     categoryId: 1,
//     img: "https://i.ibb.co/mc3v6hL/modSeed.jpg",
//     img2: "",
//     img3: "",
//     title: "Mod.Seed - Balance Boards",
//     description: "Tablas de equilibrio Hechas a Mano Modelo Skater",
//     stock: "5",
//     offerPrice: 5999.99,
//     listPrice: 6999.99,
//     cuotas: (5999.99 / 12).toFixed(2),
//   },

//   {
//     id: 3,
//     category: "tablas",
//     categoryId: 1,
//     img: "https://i.ibb.co/gT8nXq4/modPulp.jpg",
//     img2: "",
//     img3: "",
//     title: "Mod.Pulp - Balance Boards",
//     description: "Tablas de equilibrio Hechas a Mano Modelo Simétrico",
//     stock: "5",
//     offerPrice: 5999.99,
//     listPrice: 6999.99,
//     cuotas: (5999.99 / 12).toFixed(2),
//   },

//   // REMERAS

//   {
//     id: 4,
//     category: "remeras",
//     categoryId: 2,
//     img: "https://i.ibb.co/QDJP9rh/remera-Basic1.png",
//     img2: "https://i.ibb.co/41Xd2TS/remera-Basic2.png",
//     img3: "https://i.ibb.co/2MNHhX4/remera-Basic3.png",
//     title: "Remeras Kiwi Basic",
//     description: "Remeras Basicas 100% Algodon Modelo Basico",
//     stock: "5",
//     offerPrice: 2999.99,
//     listPrice: 4999.99,
//     cuotas: (2999.99 / 12).toFixed(2),
//   },

//   {
//     id: 5,
//     category: "remeras",
//     categoryId: 2,
//     img: "https://i.ibb.co/zJM7wSt/remera-Monster1.png",
//     img2: "https://i.ibb.co/n3q0pMY/remera-Monster2.png",
//     img3: "https://i.ibb.co/wNB0J9Y/remera-Monster3.png",
//     title: "Remeras Kiwi Monster",
//     description: "Remeras Basicas 100% Algodon Modelo Monster",
//     stock: "5",
//     offerPrice: 2999.99,
//     listPrice: 4999.99,
//     cuotas: (2999.99 / 12).toFixed(2),
//   },

//   {
//     id: 6,
//     category: "remeras",
//     categoryId: 2,
//     img: "https://i.ibb.co/djyJ8SY/remera-Emoticon1.png",
//     img2: "https://i.ibb.co/qRtp5M4/remera-Emoticon2.png",
//     img3: "https://ibb.co/8YdpxzR",
//     title: "Remeras Kiwi Emoticon",
//     description: "Remeras Basicas 100% Algodon Modelo Emoticon",
//     stock: "5",
//     offerPrice: 2999.99,
//     listPrice: 4999.99,
//     cuotas: (2999.99 / 12).toFixed(2),
//   },

//   // BUZOS

//   {
//     id: 7,
//     category: "buzos",
//     categoryId: 3,
//     img: "https://i.ibb.co/QbZCnQr/buzo-Chino1.png",
//     img2: "https://i.ibb.co/KXtq4DT/buzo-Chino2.png",
//     img3: "",
//     title: "Buzo Kiwi Fortuna",
//     description: "Buzo Basico 100% Algodon Modelo Gato de la Fortuna",
//     stock: "5",
//     offerPrice: 4999.99,
//     listPrice: 5999.99,
//     cuotas: (4999.99 / 12).toFixed(2),
//   },

//   {
//     id: 8,
//     category: "buzos",
//     categoryId: 3,
//     img: "https://i.ibb.co/7zZMT3c/buzo-Kiwi1.png",
//     img2: "https://i.ibb.co/Y0FfFJX/buzo-Kiwi2.png",
//     img3: "",
//     title: "Buzos Kiwi Monster",
//     description: "Buzo Basico 100% Algodon Modelo Monster",
//     stock: "5",
//     offerPrice: 4999.99,
//     listPrice: 5999.99,
//     cuotas: (4999.99 / 12).toFixed(2),
//   },

//   {
//     id: 9,
//     category: "buzos",
//     categoryId: 3,
//     img: "https://i.ibb.co/dfGRkRG/buzo-Emoticon.png",
//     img2: "",
//     img3: "",
//     title: "Buzos Kiwi Emoticon",
//     description: "Buzo Canguro 100% Algodon Modelo Emoticon",
//     stock: "5",
//     offerPrice: 4999.99,
//     listPrice: 5999.99,
//     cuotas: (4999.99 / 12).toFixed(2),
//   },
// ];

// export { productos };
